# Site settings
title: "Notes and Stuff"
email: marco@rizzoli.me.uk
baseurl: ""
url: "http://rizzoli.me.uk/"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "https://www.gravatar.com/avatar/8c19d329a182c796d7f0df65fbfd8434?s=500&d=mm"
google_analytics: ""
disqus_account: 
github_repository: https://github.com/mrizzoli
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  mrizzoli
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
